spring:
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: https://renderspringboot.onrender.com:${server.port}
    title: API Document
    version: 1.0.0
